"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";
import { SideBar } from "@/components/containers/SideBar";
import { CollapsibleMenu } from "@/components/containers/CollapsibleMenu";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const [isPanelOpen, setIsPanelOpen] = useState<boolean>(false);

	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex w-full'>
					<SideBar setPanelOpen={setIsPanelOpen} isPanelOpen={isPanelOpen} />
					<div className='w-full'>
						<div className=''>top menu</div>
						<div className='flex w-full h-screen'>
							<CollapsibleMenu isOpen={isPanelOpen} />
							<div className='w-full'>{children}</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
